version: "3.9"
services:
  pgdb:
    container_name: pgdb
    image: postgres:14.5
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: ${POSTGRES_USER:-pguser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pgpass}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/var/lib/postgresql/data
    networks:
      - db-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U pguser -d db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - ${PGADMIN_PORT:-5050}:80
    depends_on:
      - pgdb
    networks:
      - db-net
    restart: unless-stopped

  adminer:
    image: adminer
    restart: unless-stopped
    depends_on:
      - pgdb
    ports:
      - "5080:8080"
    networks:
      - db-net

  simple-spring-app:
    container_name: simple-spring-app
    image: a002k/simple-spring-app
    ports:
      - "8080:8080"
    depends_on:
      - pgdb
    networks:
      - db-net
    restart: on-failure
    environment:
      - WAIT_HOSTS=pgdb:5432, pgadmin:80, adminer:8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pgdb:5432/db
      - SPRING_DATASOURCE_USERNAME=pguser
      - SPRING_DATASOURCE_PASSWORD=pgpass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

networks:
  db-net:
    driver: bridge

volumes:
  postgres:
  pgadmin: