version: "3.9"
services:
  simple-spring-app:
    container_name: simple-spring-app
    image: a002k/simple-spring-app:latest
    ports:
      - "8080:8080"
    networks:
      - db-net
    restart: on-failure
    environment:
      - SPRING_PROFILES_ACTIVE=production

networks:
  db-net:
    driver: bridge