CREATE OR REPLACE RULE person_del_protect AS ON DELETE TO person DO INSTEAD NOTHING;
CREATE OR REPLACE RULE person_update_protect AS ON UPDATE TO person DO INSTEAD NOTHING;

CREATE OR REPLACE RULE player_del_protect AS ON DELETE TO player DO INSTEAD NOTHING;
CREATE OR REPLACE RULE player_update_protect AS ON UPDATE TO player DO INSTEAD NOTHING;